### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by dmaisano** [MhMadHamster/vscode-postcss-language#13]
I am having trouble getting PostCSS mixins to work, the syntax is correct and the intellisense is spitting out syntax errors, everything else with the package works great it's just a bit of a bother to see errors when working with PostCSS that should be valid. Is there any work around for this, for that matter is anyone else experiencing a similar issue.

![postcss mixins](https://user-images.githubusercontent.com/17837521/28285530-2155d52a-6b03-11e7-8b29-e832a780f84b.png)

**Comment by MhMadHamster** [comment]
Hello, the plugin validation not yet supporting custom syntax validation since you can install various plugins (such as define-plugin) which adding new syntax, as a workaround you can add following setting in your File - Preference - Settings `"postcss.validate": false`, and validate your code with smth like stylelint.

**Comment by dmaisano** [comment]
Sounds good will do, I'll take a look into stylelint for validation. Best of luck with the package, I really enjoy the autocomplete it works well!
