### ISSUE TITLE
Intellisense (autocomplete) variables from another file?

### ISSUE THREAD

**Issue by onetrev** [MhMadHamster/vscode-postcss-language#19]
I don't suppose it would be possible to add support so that CSS Next variables in a separate file like below could pop up in my Intellisense autocomplete when I start typing something like `z-index: var(--zind` in another file? 

```
:root {
  --zindex-dropdown: 1000;
  --zindex-overlay: 2000;
  --zindex-modal: 3000;
}
```

It would be hugely amazingly helpful if this were possible though!

**Comment by onetrev** [comment]
Similarly, if the above autocomplete is possible, then I'm assuming then things like "Go to Definition" and _Ctrl+Hover_ to get definition preview, as you can do with Sass variables for example ([with this extension](https://github.com/mrmlnc/vscode-scss)), would be possible too for PostCSS / cssnext custom properties (variables)? And that would be equally huge to be able to have support for that. Cheers!

**Comment by MhMadHamster** [comment]
hello, I'm currently not using this plugin actively and originally it was created just for proper syntax highlighting, and to add the feature you're asking for, it would probably require writing vscode-postcss-languageservice from scratch since as far as I know vscode don't have one yet.
Sorry for the delayed answer.
